version: 2
updates:
  # TODO - Breaks requirements.txt.  Try and create a monthly that runs `make
  # venv-update-requirements`.
  # - package-ecosystem: pip
  #   directory: /
  #   schedule:
  #     interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
